#!/bin/sh

# Inspired by http://amattn.com/p/tutorial_postgresql_usage_examples_with_docker.html

cp /etc/postgresql/9.4/main/postgresql.conf /data/postgresql.conf
cp /etc/postgresql/9.4/main/pg_hba.conf /data/pg_hba.conf

sed -i '/^data_directory*/ s|/var/lib/postgresql/9.4/main|/data/main|' /data/postgresql.conf
sed -i '/^hba_file*/ s|/etc/postgresql/9.4/main/pg_hba.conf|/data/pg_hba.conf|' /data/postgresql.conf

mkdir -p /data/main
chown postgres /data/*
chgrp postgres /data/*
chmod 700 /data/main
su postgres --command "/usr/lib/postgresql/9.4/bin/initdb -D /data/main"
# cp /postgresql.conf /data/postgresql.conf
# cp /pg_hba.conf /data/pg_hba.conf

# NOT SECURE! Modify according to your setup
sed -i "/^#listen_addresses/i listen_addresses='*'" /data/postgresql.conf
sed -i "/^# DO NOT DISABLE\!/i # Allow access from any IP address" /data/pg_hba.conf
sed -i "/^# DO NOT DISABLE\!/i host all all 0.0.0.0/0 md5\n\n\n" /data/pg_hba.conf

# Start postgres
su postgres --command "/usr/lib/postgresql/9.4/bin/postgres -D /data/main -c config_file=/data/postgresql.conf" &

sleep 5

# As the user postgres, create a user named docker
su postgres --command 'createuser -P -d -r -s docker'

su postgres --command 'psql -U postgres -c "ALTER USER docker with password '"'docker'"';"'

# As the user postgres, create a db docker owned by postgres user docker
su postgres --command 'createdb -O docker docker'

# Inspired by https://github.com/vvlad/dockerfiles-postgresql-9.3

password=${MASTER_PASSWORD:-$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 32)}
su postgres --command 'psql -U postgres -c "ALTER USER postgres with password '"'$password'"';" >/dev/null 2>&1'

echo " ** USER: postgres"
echo " ** PASSWORD: $password"

pgtune -i /data/postgresql.conf -o /data/postgresql.conf  -TWeb -M`free  -ob| grep Mem: | awk '{ printf "%d",$2 }'`

# Shutdown postgres
su postgres --command '/usr/lib/postgresql/9.4/bin/pg_ctl --pgdata=/data/main stop'

# CMD	["/bin/su", "postgres", "-c", "/usr/lib/postgresql/9.4/bin/postgres -D /data/main -c config_file=/data/postgresql.conf"]
